#!/bin/sh
set -e

print_usage() {
    echo "Usage: $0 [init|build|format|run]" >&2
    exit 1
}

if [ "$#" -lt 1 ]; then
    print_usage
fi

cmdname="$0"
subcmd="$1"
shift

case "$subcmd" in
    init)
        rm -rf build
        meson setup build "$@"
    ;;

    build)
        ninja -C build "$@"
    ;;

    format)
        ninja -C build clang-format "$@"
    ;;

    run)
        if ! (ninja -C build >/dev/null); then
            echo "Build failed. Rebuilding to generate error messages."
            ninja -C build
            exit 1
        else
            ./build/cydbg "$@"
        fi
    ;;

    *)
        print_usage
    ;;
esac
